// ==========================================
// PRE-COMPILED BOSS DANMAKU GENERATORS
// Auto-generated by tools/compile.js
// ==========================================

window.compiledBossDanmaku = window.compiledBossDanmaku || {};
window.compiledDanmaku = window.compiledDanmaku || {};
window.compiledBossDanmakuList = [
  {
    "id": "spell_reimu_non_1",
    "name": "",
    "hp": 900,
    "duration": 25,
    "x_offset": 0,
    "y_offset": 0,
    "despawnTime": 1.5,
    "emitterScript": "\nwhile (true) {\n    aimAtTarget()\n    spawnRing(\"normal\", \"#ff3344\", 170, angle, 16, 0, 0, 20, \"ohuda\", \"relative\", 6)\n    wait(0.35)\n    spawnRing(\"normal\", \"#33aaff\", 210, angle + 11.25, 16, 0, 0, 20, \"kome\", \"relative\", 4)\n    wait(0.35)\n}\n        ",
    "bulletScript": "\nspeed = 170\n        ",
    "magicCircleScript": ""
  },
  {
    "id": "spell_reimu_1",
    "name": "霊符「夢想封印 集」",
    "hp": 1200,
    "duration": 30,
    "x_offset": 0,
    "y_offset": 0,
    "despawnTime": 1.5,
    "emitterScript": "\nwhile (true) {\n    aimAtTarget()\n    spawnRing(\"normal\", \"#ff4466\", 160, angle, 36, 0, 0, 20, \"ohuda\", \"relative\", 6)\n    wait(0.2)\n    spawnRing(\"normal\", \"#ffcc00\", 220, angle + 15, 8, 0, 0, 6, \"star\", \"relative\", 5)\n    wait(0.25)\n}\n        ",
    "bulletScript": "\n        if (color == #ff4466) {\n            speed = 500\n            for (let g = 0; g < 20; g++) {\n                speed += -25\n                wait(0.04)\n            }\n            aimAtTarget()\n            wait(0.2)\n            spriteAngle = angle\n            color = #ff6600\n        }\n        if (color == #ff6600) {\n            speed = 750\n            for (let g = 0; g < 20; g++) {\n                speed += -25 * 1.5\n                wait(0.04)\n            }\n            aimAtTarget()\n            wait(0.2)\n            spriteAngle = angle\n            color = #9900ff\n            speed = 300\n        }\n        ",
    "magicCircleScript": ""
  },
  {
    "id": "spell_reimu_non_2",
    "name": "",
    "hp": 1100,
    "duration": 25,
    "x_offset": 0,
    "y_offset": 0,
    "despawnTime": 1.5,
    "emitterScript": "\nwhile (true) {\n    aimAtTarget()\n    spawnRing(\"normal\", \"#ff2255\", 150, angle, 8, 0, 0, 16, \"onmyoutama\", \"relative\", 12)\n    for (let k = 0; k < 3; k++) {\n        spawnRing(\"normal\", \"#ffaa33\", 190 + k * 20, angle + rand(-15, 15), 12, 0, 0, 20, \"ohuda\", \"relative\", 6)\n        wait(0.1)\n    }\n    wait(0.4)\n}\n        ",
    "bulletScript": "\nspeed = 170\n        ",
    "magicCircleScript": ""
  },
  {
    "id": "spell_reimu_2",
    "name": "夢境「二重結界」",
    "hp": 1800,
    "duration": 35,
    "x_offset": 0,
    "y_offset": 0,
    "despawnTime": 1.5,
    "emitterScript": "\nwhile (true) {\n    aimAtTarget()\n    spawnRing(\"normal\", \"#ff3333\", 140, angle, 6, 0, 0, 16, \"onmyoutama\", \"relative\", 12)\n    for (let i = 0; i < 4; i++) {\n        spawnRing(\"normal\", \"#33ccff\", 200, angle + i * 15, 10, 0, 0, 20, \"ohuda\", \"relative\", 6)\n        wait(0.12)\n    }\n    wait(0.6)\n}\n        ",
    "bulletScript": "\nspeed = 180\nbounce()\nspriteAngle = angle\nif (isBounced) {\n    color = \"#ff8800\"\n    speed = 220\n}\n        ",
    "magicCircleScript": ""
  },
  {
    "id": "spell_rush1_non_1",
    "name": "",
    "hp": 1000,
    "duration": 25,
    "x_offset": 0,
    "y_offset": 0,
    "despawnTime": 1.5,
    "emitterScript": "\nwhile (true) {\n    ey = 300\n    aimAtTarget()\n    spawnWay(\"normal\", \"#ff3333\", 500, angle, 2, 30, 0, 0, 9, \"dangan\", \"relative\", \"6\")\n    spawnWay(\"normal\", \"#ff3333\", 500, angle, 3, 2, 0, 0, 9, \"dangan\", \"relative\", \"6\")\n    spawnWay(\"normal\", \"#ff3333\", 500, angle + 180, 5, 60, 0, 0, 9, \"dangan\", \"relative\", \"6\")\n    wait(0.0167 * 4)\n}\n        ",
    "bulletScript": "\n        ",
    "magicCircleScript": ""
  },
  {
    "id": "spell_rush1_1",
    "name": "飛翔「ストライクバーン」",
    "hp": 2000,
    "duration": 40,
    "x_offset": 0,
    "y_offset": 0,
    "despawnTime": 1.5,
    "emitterScript": "\n        while (true) {\n    angle = random(0,360)\n    muki = 1\n    spawnRing(\"normal\", \"#999999\", 200, angle, 36, 0, 0, 9, \"dangan\", \"relative\", \"6\")\n    spawnRing(\"normal\", \"#999999\", 300, angle, 36, 0, 0, 9, \"dangan\", \"relative\", \"6\")\n    spawnRing(\"normal\", \"#999999\", 400, angle, 36, 0, 0, 9, \"dangan\", \"relative\", \"6\")\n    spawnRing(\"normal\", \"#999999\", 500, angle, 36, 0, 0, 9, \"dangan\", \"relative\", \"6\")\n    muki = -1\n    spawnRing(\"normal\", \"#999999\", 200, angle, 36, 0, 0, 9, \"dangan\", \"relative\", \"6\")\n    spawnRing(\"normal\", \"#999999\", 300, angle, 36, 0, 0, 9, \"dangan\", \"relative\", \"6\")\n    spawnRing(\"normal\", \"#999999\", 400, angle, 36, 0, 0, 9, \"dangan\", \"relative\", \"6\")\n    spawnRing(\"normal\", \"#999999\", 500, angle, 36, 0, 0, 9, \"dangan\", \"relative\", \"6\")\n    muki = 0\n    spawnRing(\"normal\", \"#ff3333\", 200, angle, 36, 0, 0, 9, \"dangan\", \"relative\", \"6\")\n    spawnRing(\"normal\", \"#ff3333\", 300, angle, 36, 0, 0, 9, \"dangan\", \"relative\", \"6\")\n    spawnRing(\"normal\", \"#ff3333\", 400, angle, 36, 0, 0, 9, \"dangan\", \"relative\", \"6\")\n    spawnRing(\"normal\", \"#ff3333\", 500, angle, 36, 0, 0, 9, \"dangan\", \"relative\", \"6\")\n    wait(1.67)\n}\n        ",
    "bulletScript": "\nif (color==#999999) {\n    if (frame ==20..21) {\n        once {\n            angle += 10 * muki\n            spriteAngle = angle\n        }\n    }\n}\n        ",
    "magicCircleScript": "\n        \n        "
  }
];
window.bossDanmakuList = window.compiledBossDanmakuList;

window.compiledBossDanmaku['spell_reimu_non_1'] = window.compiledDanmaku['spell_reimu_non_1'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    if (_util.executeBlock({ type: 'aim_at_target', }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ff3344", speed: "170", angle: "angle", count: "16", offsetX: "0", offsetY: "0", radius: "20", bulletImage: "ohuda", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
      yield;
    }
    state.waitTimer = Math.max(0.0167, 0.35);
    yield;
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#33aaff", speed: "210", angle: "angle + 11.25", count: "16", offsetX: "0", offsetY: "0", radius: "20", bulletImage: "kome", coordMode: "relative", hitRadius: "4", }, state, b, attacker, target, _util)) {
      yield;
    }
    state.waitTimer = Math.max(0.0167, 0.35);
    yield;
  }
};
window.compiledBossDanmaku['spell_reimu_non_1_bullet'] = window.compiledDanmaku['spell_reimu_non_1_bullet'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    vars['speed'] = 170;
    state.waitTimer = Math.max(state.waitTimer || 0, 0.01);
    yield;
  }
};
window.compiledBossDanmaku['spell_reimu_non_1_magic'] = window.compiledDanmaku['spell_reimu_non_1_magic'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};

window.compiledBossDanmaku['spell_reimu_1'] = window.compiledDanmaku['spell_reimu_1'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    if (_util.executeBlock({ type: 'aim_at_target', }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ff4466", speed: "160", angle: "angle", count: "36", offsetX: "0", offsetY: "0", radius: "20", bulletImage: "ohuda", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
      yield;
    }
    state.waitTimer = Math.max(0.0167, 0.2);
    yield;
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ffcc00", speed: "220", angle: "angle + 15", count: "8", offsetX: "0", offsetY: "0", radius: "6", bulletImage: "star", coordMode: "relative", hitRadius: "5", }, state, b, attacker, target, _util)) {
      yield;
    }
    state.waitTimer = Math.max(0.0167, 0.25);
    yield;
  }
};
window.compiledBossDanmaku['spell_reimu_1_bullet'] = window.compiledDanmaku['spell_reimu_1_bullet'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    if ((String((vars.color !== undefined ? vars.color : "")).trim().toLowerCase() === String("#ff4466").trim().toLowerCase())) {
      vars['speed'] = 500;
      let _prev_g_148 = vars['g'];
      for (let _loopIdx_148 = 0, _limit_148 = Math.round(20); _loopIdx_148 < _limit_148; _loopIdx_148++) {
        vars['g'] = _loopIdx_148;
        vars['speed'] = (vars['speed'] || 0) + (-25);
        state.waitTimer = Math.max(0.0167, 0.04);
        yield;
      }
      vars['g'] = _prev_g_148;
      if (_util.executeBlock({ type: 'aim_at_target', }, state, b, attacker, target, _util)) {
        yield;
      }
      state.waitTimer = Math.max(0.0167, 0.2);
      yield;
      vars['spriteAngle'] = (vars.angle !== undefined ? vars.angle : 0);
      vars['color'] = "#ff6600";
    }
    if ((String((vars.color !== undefined ? vars.color : "")).trim().toLowerCase() === String("#ff6600").trim().toLowerCase())) {
      vars['speed'] = 750;
      let _prev_g_149 = vars['g'];
      for (let _loopIdx_149 = 0, _limit_149 = Math.round(20); _loopIdx_149 < _limit_149; _loopIdx_149++) {
        vars['g'] = _loopIdx_149;
        vars['speed'] = (vars['speed'] || 0) + (-25 * 1.5);
        state.waitTimer = Math.max(0.0167, 0.04);
        yield;
      }
      vars['g'] = _prev_g_149;
      if (_util.executeBlock({ type: 'aim_at_target', }, state, b, attacker, target, _util)) {
        yield;
      }
      state.waitTimer = Math.max(0.0167, 0.2);
      yield;
      vars['spriteAngle'] = (vars.angle !== undefined ? vars.angle : 0);
      vars['color'] = "#9900ff";
      vars['speed'] = 300;
    }
    state.waitTimer = Math.max(state.waitTimer || 0, 0.01);
    yield;
  }
};
window.compiledBossDanmaku['spell_reimu_1_magic'] = window.compiledDanmaku['spell_reimu_1_magic'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};

window.compiledBossDanmaku['spell_reimu_non_2'] = window.compiledDanmaku['spell_reimu_non_2'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    if (_util.executeBlock({ type: 'aim_at_target', }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ff2255", speed: "150", angle: "angle", count: "8", offsetX: "0", offsetY: "0", radius: "16", bulletImage: "onmyoutama", coordMode: "relative", hitRadius: "12", }, state, b, attacker, target, _util)) {
      yield;
    }
    let _prev_k_150 = vars['k'];
    for (let _loopIdx_150 = 0, _limit_150 = Math.round(3); _loopIdx_150 < _limit_150; _loopIdx_150++) {
      vars['k'] = _loopIdx_150;
      if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ffaa33", speed: "190 + k * 20", angle: "angle + rand(-15, 15)", count: "12", offsetX: "0", offsetY: "0", radius: "20", bulletImage: "ohuda", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
        yield;
      }
      state.waitTimer = Math.max(0.0167, 0.1);
      yield;
    }
    vars['k'] = _prev_k_150;
    state.waitTimer = Math.max(0.0167, 0.4);
    yield;
  }
};
window.compiledBossDanmaku['spell_reimu_non_2_bullet'] = window.compiledDanmaku['spell_reimu_non_2_bullet'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    vars['speed'] = 170;
    state.waitTimer = Math.max(state.waitTimer || 0, 0.01);
    yield;
  }
};
window.compiledBossDanmaku['spell_reimu_non_2_magic'] = window.compiledDanmaku['spell_reimu_non_2_magic'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};

window.compiledBossDanmaku['spell_reimu_2'] = window.compiledDanmaku['spell_reimu_2'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    if (_util.executeBlock({ type: 'aim_at_target', }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ff3333", speed: "140", angle: "angle", count: "6", offsetX: "0", offsetY: "0", radius: "16", bulletImage: "onmyoutama", coordMode: "relative", hitRadius: "12", }, state, b, attacker, target, _util)) {
      yield;
    }
    let _prev_i_151 = vars['i'];
    for (let _loopIdx_151 = 0, _limit_151 = Math.round(4); _loopIdx_151 < _limit_151; _loopIdx_151++) {
      vars['i'] = _loopIdx_151;
      if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#33ccff", speed: "200", angle: "angle + i * 15", count: "10", offsetX: "0", offsetY: "0", radius: "20", bulletImage: "ohuda", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
        yield;
      }
      state.waitTimer = Math.max(0.0167, 0.12);
      yield;
    }
    vars['i'] = _prev_i_151;
    state.waitTimer = Math.max(0.0167, 0.6);
    yield;
  }
};
window.compiledBossDanmaku['spell_reimu_2_bullet'] = window.compiledDanmaku['spell_reimu_2_bullet'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    vars['speed'] = 180;
    if (_util.executeBlock({ type: 'bounce', }, state, b, attacker, target, _util)) {
      yield;
    }
    vars['spriteAngle'] = (vars.angle !== undefined ? vars.angle : 0);
    if (!!((vars.isBounced !== undefined ? vars.isBounced : 0))) {
      vars['color'] = "#ff8800";
      vars['speed'] = 220;
    }
    state.waitTimer = Math.max(state.waitTimer || 0, 0.01);
    yield;
  }
};
window.compiledBossDanmaku['spell_reimu_2_magic'] = window.compiledDanmaku['spell_reimu_2_magic'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};

window.compiledBossDanmaku['spell_rush1_non_1'] = window.compiledDanmaku['spell_rush1_non_1'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    vars['ey'] = 300;
    if (_util.executeBlock({ type: 'aim_at_target', }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_way', bulletType: "normal", color: "#ff3333", speed: "500", angle: "angle", count: "2", spread: "30", offsetX: "0", offsetY: "0", radius: "9", bulletImage: "dangan", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_way', bulletType: "normal", color: "#ff3333", speed: "500", angle: "angle", count: "3", spread: "2", offsetX: "0", offsetY: "0", radius: "9", bulletImage: "dangan", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_way', bulletType: "normal", color: "#ff3333", speed: "500", angle: "angle + 180", count: "5", spread: "60", offsetX: "0", offsetY: "0", radius: "9", bulletImage: "dangan", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
      yield;
    }
    state.waitTimer = Math.max(0.0167, 0.0167 * 4);
    yield;
  }
};
window.compiledBossDanmaku['spell_rush1_non_1_bullet'] = window.compiledDanmaku['spell_rush1_non_1_bullet'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};
window.compiledBossDanmaku['spell_rush1_non_1_magic'] = window.compiledDanmaku['spell_rush1_non_1_magic'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};

window.compiledBossDanmaku['spell_rush1_1'] = window.compiledDanmaku['spell_rush1_1'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    vars['angle'] = random(0,360);
    vars['muki'] = 1;
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#999999", speed: "200", angle: "angle", count: "36", offsetX: "0", offsetY: "0", radius: "9", bulletImage: "dangan", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#999999", speed: "300", angle: "angle", count: "36", offsetX: "0", offsetY: "0", radius: "9", bulletImage: "dangan", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#999999", speed: "400", angle: "angle", count: "36", offsetX: "0", offsetY: "0", radius: "9", bulletImage: "dangan", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#999999", speed: "500", angle: "angle", count: "36", offsetX: "0", offsetY: "0", radius: "9", bulletImage: "dangan", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
      yield;
    }
    vars['muki'] = -1;
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#999999", speed: "200", angle: "angle", count: "36", offsetX: "0", offsetY: "0", radius: "9", bulletImage: "dangan", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#999999", speed: "300", angle: "angle", count: "36", offsetX: "0", offsetY: "0", radius: "9", bulletImage: "dangan", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#999999", speed: "400", angle: "angle", count: "36", offsetX: "0", offsetY: "0", radius: "9", bulletImage: "dangan", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#999999", speed: "500", angle: "angle", count: "36", offsetX: "0", offsetY: "0", radius: "9", bulletImage: "dangan", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
      yield;
    }
    vars['muki'] = 0;
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ff3333", speed: "200", angle: "angle", count: "36", offsetX: "0", offsetY: "0", radius: "9", bulletImage: "dangan", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ff3333", speed: "300", angle: "angle", count: "36", offsetX: "0", offsetY: "0", radius: "9", bulletImage: "dangan", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ff3333", speed: "400", angle: "angle", count: "36", offsetX: "0", offsetY: "0", radius: "9", bulletImage: "dangan", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ff3333", speed: "500", angle: "angle", count: "36", offsetX: "0", offsetY: "0", radius: "9", bulletImage: "dangan", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
      yield;
    }
    state.waitTimer = Math.max(0.0167, 1.67);
    yield;
  }
};
window.compiledBossDanmaku['spell_rush1_1_bullet'] = window.compiledDanmaku['spell_rush1_1_bullet'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    if ((String((vars.color !== undefined ? vars.color : "")).trim().toLowerCase() === String("#999999").trim().toLowerCase())) {
      if (!!((((vars.frame !== undefined ? vars.frame : 0)) >= (20) && ((vars.frame !== undefined ? vars.frame : 0)) <= (21)))) {
        if (!state.onceMap) state.onceMap = {};
        if (!state.onceMap['hqrye7kof']) {
          state.onceMap['hqrye7kof'] = true;
          vars['angle'] = (vars['angle'] || 0) + (10 * (vars.muki !== undefined ? vars.muki : 0));
          vars['spriteAngle'] = (vars.angle !== undefined ? vars.angle : 0);
        }
      }
    }
    state.waitTimer = Math.max(state.waitTimer || 0, 0.01);
    yield;
  }
};
window.compiledBossDanmaku['spell_rush1_1_magic'] = window.compiledDanmaku['spell_rush1_1_magic'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};

