// ==========================================
// PRE-COMPILED BOSS DANMAKU GENERATORS
// Auto-generated by tools/compile.js
// ==========================================

window.compiledBossDanmaku = window.compiledBossDanmaku || {};
window.compiledDanmaku = window.compiledDanmaku || {};
window.compiledBossDanmakuList = [
  {
    "id": "spell_reimu_non_1",
    "name": "",
    "hp": 900,
    "duration": 25,
    "x_offset": 0,
    "y_offset": 0,
    "despawnTime": 1.5,
    "emitterScript": "\nwhile (true) {\n    aimAtTarget()\n    spawnRing(\"normal\", \"#ff3344\", 170, angle, 16, 0, 0, 20, \"ohuda\", \"relative\", 6)\n    wait(0.35)\n    spawnRing(\"normal\", \"#33aaff\", 210, angle + 11.25, 16, 0, 0, 20, \"kome\", \"relative\", 4)\n    wait(0.35)\n}\n        ",
    "bulletScript": "\nspeed = 170\n        ",
    "magicCircleScript": ""
  },
  {
    "id": "spell_reimu_1",
    "name": "霊符「夢想封印 集」",
    "hp": 1200,
    "duration": 30,
    "x_offset": 0,
    "y_offset": 0,
    "despawnTime": 1.5,
    "emitterScript": "\nwhile (true) {\n    aimAtTarget()\n    spawnRing(\"normal\", \"#ff4466\", 160, angle, 36, 0, 0, 20, \"ohuda\", \"relative\", 6)\n    wait(0.2)\n    spawnRing(\"normal\", \"#ffcc00\", 220, angle + 15, 8, 0, 0, 6, \"star\", \"relative\", 5)\n    wait(0.25)\n}\n        ",
    "bulletScript": "\n        if (color == #ff4466) {\n            speed = 500\n            for (let g = 0; g < 20; g++) {\n                speed += -25\n                wait(0.04)\n            }\n            aimAtTarget()\n            wait(0.2)\n            spriteAngle = angle\n            color = #ff6600\n        }\n        if (color == #ff6600) {\n            speed = 750\n            for (let g = 0; g < 20; g++) {\n                speed += -25 * 1.5\n                wait(0.04)\n            }\n            aimAtTarget()\n            wait(0.2)\n            spriteAngle = angle\n            color = #9900ff\n            speed = 300\n        }\n        ",
    "magicCircleScript": ""
  },
  {
    "id": "spell_reimu_non_2",
    "name": "",
    "hp": 1100,
    "duration": 25,
    "x_offset": 0,
    "y_offset": 0,
    "despawnTime": 1.5,
    "emitterScript": "\nwhile (true) {\n    aimAtTarget()\n    spawnRing(\"normal\", \"#ff2255\", 150, angle, 8, 0, 0, 16, \"onmyoutama\", \"relative\", 12)\n    for (let k = 0; k < 3; k++) {\n        spawnRing(\"normal\", \"#ffaa33\", 190 + k * 20, angle + rand(-15, 15), 12, 0, 0, 20, \"ohuda\", \"relative\", 6)\n        wait(0.1)\n    }\n    wait(0.4)\n}\n        ",
    "bulletScript": "\nspeed = 170\n        ",
    "magicCircleScript": ""
  },
  {
    "id": "spell_reimu_2",
    "name": "夢境「二重結界」",
    "hp": 1800,
    "duration": 35,
    "x_offset": 0,
    "y_offset": 0,
    "despawnTime": 1.5,
    "emitterScript": "\nwhile (true) {\n    aimAtTarget()\n    spawnRing(\"normal\", \"#ff3333\", 140, angle, 6, 0, 0, 16, \"onmyoutama\", \"relative\", 12)\n    for (let i = 0; i < 4; i++) {\n        spawnRing(\"normal\", \"#33ccff\", 200, angle + i * 15, 10, 0, 0, 20, \"ohuda\", \"relative\", 6)\n        wait(0.12)\n    }\n    wait(0.6)\n}\n        ",
    "bulletScript": "\nspeed = 180\nbounce()\nspriteAngle = angle\nif (isBounced) {\n    color = \"#ff8800\"\n    speed = 220\n}\n        ",
    "magicCircleScript": ""
  },
  {
    "id": "spell_marisa_non_1",
    "name": "",
    "hp": 1000,
    "duration": 25,
    "x_offset": 0,
    "y_offset": 0,
    "despawnTime": 1.5,
    "emitterScript": "\nwhile (true) {\n    angle += 5\n    spawnRing(\"normal\", \"#ffee22\", 190, angle, 12, 0, 0, 8, \"star\", \"relative\", 6)\n    spawnRing(\"normal\", \"#33ffcc\", 300, angle + 15, 12, 0, 0, 20, \"kome\", \"relative\", 4)\n    wait(0.2)\n}\n        ",
    "bulletScript": "\nspeed = 200\n        ",
    "magicCircleScript": ""
  },
  {
    "id": "spell_marisa_1",
    "name": "恋符「マスタースパーク・ライト」",
    "hp": 1500,
    "duration": 30,
    "x_offset": 0,
    "y_offset": 0,
    "despawnTime": 1.5,
    "emitterScript": "\nwhile (true) {\n    aimAtTarget()\n    spawnRing(\"normal\", \"#ffee33\", 180, angle, 8, 0, 0, 18, \"b_star\", \"relative\", 14)\n    for (let j = 0; j < 6; j++) {\n        spawnRing(\"normal\", \"#33ffaa\", 240, angle + rand(-30, 30), 12, 0, 0, 8, \"star\", \"relative\", 6)\n        wait(0.08)\n    }\n    wait(0.5)\n}\n        ",
    "bulletScript": "\nspeed = 220\nangle_velocity = 20\n        ",
    "magicCircleScript": ""
  },
  {
    "id": "spell_marisa_non_2",
    "name": "",
    "hp": 1300,
    "duration": 25,
    "x_offset": 0,
    "y_offset": 0,
    "despawnTime": 1.5,
    "emitterScript": "\nwhile (true) {\n    aimAtTarget()\n    spawnRing(\"normal\", \"#ff9900\", 170, angle, 6, 0, 0, 18, \"b_star\", \"relative\", 14)\n    for (let m = 0; m < 4; m++) {\n        spawnRing(\"normal\", \"#ffff44\", 220 + m * 15, angle + m * 10, 10, 0, 0, 8, \"star\", \"relative\", 6)\n        wait(0.08)\n    }\n    wait(0.35)\n}\n        ",
    "bulletScript": "\nspeed = 210\n        ",
    "magicCircleScript": ""
  },
  {
    "id": "spell_marisa_2",
    "name": "彗星「ブレイジングスター」",
    "hp": 2200,
    "duration": 40,
    "x_offset": 0,
    "y_offset": 0,
    "despawnTime": 1.5,
    "emitterScript": "\nwhile (true) {\n    aimAtTarget()\n    for (let k = 0; k < 16; k++) {\n        spawnRing(\"normal\", \"#ffdd44\", 260, angle + k * 12, 16, 0, 0, 10, \"star\", \"relative\", 7)\n        wait(0.06)\n    }\n    wait(0.7)\n}\n        ",
    "bulletScript": "\nspeed = 240\nwait(0.3)\nangle_velocity = -15\n        ",
    "magicCircleScript": ""
  }
];
window.bossDanmakuList = window.compiledBossDanmakuList;

window.compiledBossDanmaku['spell_reimu_non_1'] = window.compiledDanmaku['spell_reimu_non_1'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    if (_util.executeBlock({ type: 'aim_at_target', }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ff3344", speed: "170", angle: "angle", count: "16", offsetX: "0", offsetY: "0", radius: "20", bulletImage: "ohuda", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
      yield;
    }
    state.waitTimer = Math.max(0.0167, 0.35);
    yield;
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#33aaff", speed: "210", angle: "angle + 11.25", count: "16", offsetX: "0", offsetY: "0", radius: "20", bulletImage: "kome", coordMode: "relative", hitRadius: "4", }, state, b, attacker, target, _util)) {
      yield;
    }
    state.waitTimer = Math.max(0.0167, 0.35);
    yield;
  }
};
window.compiledBossDanmaku['spell_reimu_non_1_bullet'] = window.compiledDanmaku['spell_reimu_non_1_bullet'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    vars['speed'] = 170;
    state.waitTimer = Math.max(state.waitTimer || 0, 0.01);
    yield;
  }
};
window.compiledBossDanmaku['spell_reimu_non_1_magic'] = window.compiledDanmaku['spell_reimu_non_1_magic'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};

window.compiledBossDanmaku['spell_reimu_1'] = window.compiledDanmaku['spell_reimu_1'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    if (_util.executeBlock({ type: 'aim_at_target', }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ff4466", speed: "160", angle: "angle", count: "36", offsetX: "0", offsetY: "0", radius: "20", bulletImage: "ohuda", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
      yield;
    }
    state.waitTimer = Math.max(0.0167, 0.2);
    yield;
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ffcc00", speed: "220", angle: "angle + 15", count: "8", offsetX: "0", offsetY: "0", radius: "6", bulletImage: "star", coordMode: "relative", hitRadius: "5", }, state, b, attacker, target, _util)) {
      yield;
    }
    state.waitTimer = Math.max(0.0167, 0.25);
    yield;
  }
};
window.compiledBossDanmaku['spell_reimu_1_bullet'] = window.compiledDanmaku['spell_reimu_1_bullet'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    if ((String((vars.color !== undefined ? vars.color : "")).trim().toLowerCase() === String("#ff4466").trim().toLowerCase())) {
      vars['speed'] = 500;
      let _prev_g_148 = vars['g'];
      for (let _loopIdx_148 = 0, _limit_148 = Math.round(20); _loopIdx_148 < _limit_148; _loopIdx_148++) {
        vars['g'] = _loopIdx_148;
        vars['speed'] = (vars['speed'] || 0) + (-25);
        state.waitTimer = Math.max(0.0167, 0.04);
        yield;
      }
      vars['g'] = _prev_g_148;
      if (_util.executeBlock({ type: 'aim_at_target', }, state, b, attacker, target, _util)) {
        yield;
      }
      state.waitTimer = Math.max(0.0167, 0.2);
      yield;
      vars['spriteAngle'] = (vars.angle !== undefined ? vars.angle : 0);
      vars['color'] = "#ff6600";
    }
    if ((String((vars.color !== undefined ? vars.color : "")).trim().toLowerCase() === String("#ff6600").trim().toLowerCase())) {
      vars['speed'] = 750;
      let _prev_g_149 = vars['g'];
      for (let _loopIdx_149 = 0, _limit_149 = Math.round(20); _loopIdx_149 < _limit_149; _loopIdx_149++) {
        vars['g'] = _loopIdx_149;
        vars['speed'] = (vars['speed'] || 0) + (-25 * 1.5);
        state.waitTimer = Math.max(0.0167, 0.04);
        yield;
      }
      vars['g'] = _prev_g_149;
      if (_util.executeBlock({ type: 'aim_at_target', }, state, b, attacker, target, _util)) {
        yield;
      }
      state.waitTimer = Math.max(0.0167, 0.2);
      yield;
      vars['spriteAngle'] = (vars.angle !== undefined ? vars.angle : 0);
      vars['color'] = "#9900ff";
      vars['speed'] = 300;
    }
    state.waitTimer = Math.max(state.waitTimer || 0, 0.01);
    yield;
  }
};
window.compiledBossDanmaku['spell_reimu_1_magic'] = window.compiledDanmaku['spell_reimu_1_magic'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};

window.compiledBossDanmaku['spell_reimu_non_2'] = window.compiledDanmaku['spell_reimu_non_2'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    if (_util.executeBlock({ type: 'aim_at_target', }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ff2255", speed: "150", angle: "angle", count: "8", offsetX: "0", offsetY: "0", radius: "16", bulletImage: "onmyoutama", coordMode: "relative", hitRadius: "12", }, state, b, attacker, target, _util)) {
      yield;
    }
    let _prev_k_150 = vars['k'];
    for (let _loopIdx_150 = 0, _limit_150 = Math.round(3); _loopIdx_150 < _limit_150; _loopIdx_150++) {
      vars['k'] = _loopIdx_150;
      if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ffaa33", speed: "190 + k * 20", angle: "angle + rand(-15, 15)", count: "12", offsetX: "0", offsetY: "0", radius: "20", bulletImage: "ohuda", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
        yield;
      }
      state.waitTimer = Math.max(0.0167, 0.1);
      yield;
    }
    vars['k'] = _prev_k_150;
    state.waitTimer = Math.max(0.0167, 0.4);
    yield;
  }
};
window.compiledBossDanmaku['spell_reimu_non_2_bullet'] = window.compiledDanmaku['spell_reimu_non_2_bullet'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    vars['speed'] = 170;
    state.waitTimer = Math.max(state.waitTimer || 0, 0.01);
    yield;
  }
};
window.compiledBossDanmaku['spell_reimu_non_2_magic'] = window.compiledDanmaku['spell_reimu_non_2_magic'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};

window.compiledBossDanmaku['spell_reimu_2'] = window.compiledDanmaku['spell_reimu_2'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    if (_util.executeBlock({ type: 'aim_at_target', }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ff3333", speed: "140", angle: "angle", count: "6", offsetX: "0", offsetY: "0", radius: "16", bulletImage: "onmyoutama", coordMode: "relative", hitRadius: "12", }, state, b, attacker, target, _util)) {
      yield;
    }
    let _prev_i_151 = vars['i'];
    for (let _loopIdx_151 = 0, _limit_151 = Math.round(4); _loopIdx_151 < _limit_151; _loopIdx_151++) {
      vars['i'] = _loopIdx_151;
      if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#33ccff", speed: "200", angle: "angle + i * 15", count: "10", offsetX: "0", offsetY: "0", radius: "20", bulletImage: "ohuda", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
        yield;
      }
      state.waitTimer = Math.max(0.0167, 0.12);
      yield;
    }
    vars['i'] = _prev_i_151;
    state.waitTimer = Math.max(0.0167, 0.6);
    yield;
  }
};
window.compiledBossDanmaku['spell_reimu_2_bullet'] = window.compiledDanmaku['spell_reimu_2_bullet'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    vars['speed'] = 180;
    if (_util.executeBlock({ type: 'bounce', }, state, b, attacker, target, _util)) {
      yield;
    }
    vars['spriteAngle'] = (vars.angle !== undefined ? vars.angle : 0);
    if (!!((vars.isBounced !== undefined ? vars.isBounced : 0))) {
      vars['color'] = "#ff8800";
      vars['speed'] = 220;
    }
    state.waitTimer = Math.max(state.waitTimer || 0, 0.01);
    yield;
  }
};
window.compiledBossDanmaku['spell_reimu_2_magic'] = window.compiledDanmaku['spell_reimu_2_magic'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};

window.compiledBossDanmaku['spell_marisa_non_1'] = window.compiledDanmaku['spell_marisa_non_1'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    vars['angle'] = (vars['angle'] || 0) + (5);
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ffee22", speed: "190", angle: "angle", count: "12", offsetX: "0", offsetY: "0", radius: "8", bulletImage: "star", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#33ffcc", speed: "300", angle: "angle + 15", count: "12", offsetX: "0", offsetY: "0", radius: "20", bulletImage: "kome", coordMode: "relative", hitRadius: "4", }, state, b, attacker, target, _util)) {
      yield;
    }
    state.waitTimer = Math.max(0.0167, 0.2);
    yield;
  }
};
window.compiledBossDanmaku['spell_marisa_non_1_bullet'] = window.compiledDanmaku['spell_marisa_non_1_bullet'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    vars['speed'] = 200;
    state.waitTimer = Math.max(state.waitTimer || 0, 0.01);
    yield;
  }
};
window.compiledBossDanmaku['spell_marisa_non_1_magic'] = window.compiledDanmaku['spell_marisa_non_1_magic'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};

window.compiledBossDanmaku['spell_marisa_1'] = window.compiledDanmaku['spell_marisa_1'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    if (_util.executeBlock({ type: 'aim_at_target', }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ffee33", speed: "180", angle: "angle", count: "8", offsetX: "0", offsetY: "0", radius: "18", bulletImage: "b_star", coordMode: "relative", hitRadius: "14", }, state, b, attacker, target, _util)) {
      yield;
    }
    let _prev_j_152 = vars['j'];
    for (let _loopIdx_152 = 0, _limit_152 = Math.round(6); _loopIdx_152 < _limit_152; _loopIdx_152++) {
      vars['j'] = _loopIdx_152;
      if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#33ffaa", speed: "240", angle: "angle + rand(-30, 30)", count: "12", offsetX: "0", offsetY: "0", radius: "8", bulletImage: "star", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
        yield;
      }
      state.waitTimer = Math.max(0.0167, 0.08);
      yield;
    }
    vars['j'] = _prev_j_152;
    state.waitTimer = Math.max(0.0167, 0.5);
    yield;
  }
};
window.compiledBossDanmaku['spell_marisa_1_bullet'] = window.compiledDanmaku['spell_marisa_1_bullet'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    vars['speed'] = 220;
    vars['angle_velocity'] = 20;
    state.waitTimer = Math.max(state.waitTimer || 0, 0.01);
    yield;
  }
};
window.compiledBossDanmaku['spell_marisa_1_magic'] = window.compiledDanmaku['spell_marisa_1_magic'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};

window.compiledBossDanmaku['spell_marisa_non_2'] = window.compiledDanmaku['spell_marisa_non_2'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    if (_util.executeBlock({ type: 'aim_at_target', }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ff9900", speed: "170", angle: "angle", count: "6", offsetX: "0", offsetY: "0", radius: "18", bulletImage: "b_star", coordMode: "relative", hitRadius: "14", }, state, b, attacker, target, _util)) {
      yield;
    }
    let _prev_m_153 = vars['m'];
    for (let _loopIdx_153 = 0, _limit_153 = Math.round(4); _loopIdx_153 < _limit_153; _loopIdx_153++) {
      vars['m'] = _loopIdx_153;
      if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ffff44", speed: "220 + m * 15", angle: "angle + m * 10", count: "10", offsetX: "0", offsetY: "0", radius: "8", bulletImage: "star", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
        yield;
      }
      state.waitTimer = Math.max(0.0167, 0.08);
      yield;
    }
    vars['m'] = _prev_m_153;
    state.waitTimer = Math.max(0.0167, 0.35);
    yield;
  }
};
window.compiledBossDanmaku['spell_marisa_non_2_bullet'] = window.compiledDanmaku['spell_marisa_non_2_bullet'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    vars['speed'] = 210;
    state.waitTimer = Math.max(state.waitTimer || 0, 0.01);
    yield;
  }
};
window.compiledBossDanmaku['spell_marisa_non_2_magic'] = window.compiledDanmaku['spell_marisa_non_2_magic'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};

window.compiledBossDanmaku['spell_marisa_2'] = window.compiledDanmaku['spell_marisa_2'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    if (_util.executeBlock({ type: 'aim_at_target', }, state, b, attacker, target, _util)) {
      yield;
    }
    let _prev_k_154 = vars['k'];
    for (let _loopIdx_154 = 0, _limit_154 = Math.round(16); _loopIdx_154 < _limit_154; _loopIdx_154++) {
      vars['k'] = _loopIdx_154;
      if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ffdd44", speed: "260", angle: "angle + k * 12", count: "16", offsetX: "0", offsetY: "0", radius: "10", bulletImage: "star", coordMode: "relative", hitRadius: "7", }, state, b, attacker, target, _util)) {
        yield;
      }
      state.waitTimer = Math.max(0.0167, 0.06);
      yield;
    }
    vars['k'] = _prev_k_154;
    state.waitTimer = Math.max(0.0167, 0.7);
    yield;
  }
};
window.compiledBossDanmaku['spell_marisa_2_bullet'] = window.compiledDanmaku['spell_marisa_2_bullet'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    vars['speed'] = 240;
    state.waitTimer = Math.max(0.0167, 0.3);
    yield;
    vars['angle_velocity'] = -15;
    state.waitTimer = Math.max(state.waitTimer || 0, 0.01);
    yield;
  }
};
window.compiledBossDanmaku['spell_marisa_2_magic'] = window.compiledDanmaku['spell_marisa_2_magic'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};

