// ==========================================
// PRE-COMPILED BOSS DANMAKU GENERATORS
// Auto-generated by tools/compile.js
// ==========================================

window.compiledBossDanmaku = window.compiledBossDanmaku || {};
window.compiledDanmaku = window.compiledDanmaku || {};
window.compiledBossDanmakuList = [
  {
    "id": "spell_reimu_non_1",
    "name": "",
    "hp": 900,
    "duration": 25,
    "x_offset": 0,
    "y_offset": 0,
    "despawnTime": 1.5,
    "emitterScript": "\nwhile (true) {\n    aimAtTarget()\n    spawnRing(\"normal\", \"#ff3344\", 170, angle, 16, 0, 0, 20, \"ohuda\", \"relative\", 6)\n    wait(0.35)\n    spawnRing(\"normal\", \"#33aaff\", 210, angle + 11.25, 16, 0, 0, 20, \"kome\", \"relative\", 4)\n    wait(0.35)\n}\n        ",
    "bulletScript": "\nspeed = 170\n        ",
    "magicCircleScript": ""
  },
  {
    "id": "spell_reimu_1",
    "name": "霊符「夢想封印 集」",
    "hp": 1200,
    "duration": 30,
    "x_offset": 0,
    "y_offset": 0,
    "despawnTime": 1.5,
    "emitterScript": "\nwhile (true) {\n    aimAtTarget()\n    spawnRing(\"normal\", \"#ff4466\", 160, angle, 36, 0, 0, 20, \"ohuda\", \"relative\", 6)\n    wait(0.2)\n    spawnRing(\"normal\", \"#ffcc00\", 220, angle + 15, 8, 0, 0, 6, \"star\", \"relative\", 5)\n    wait(0.25)\n}\n        ",
    "bulletScript": "\n        if (color == #ff4466) {\n            speed = 500\n            for (let g = 0; g < 20; g++) {\n                speed += -25\n                wait(0.04)\n            }\n            aimAtTarget()\n            wait(0.2)\n            spriteAngle = angle\n            color = #ff6600\n        }\n        if (color == #ff6600) {\n            speed = 750\n            for (let g = 0; g < 20; g++) {\n                speed += -25 * 1.5\n                wait(0.04)\n            }\n            aimAtTarget()\n            wait(0.2)\n            spriteAngle = angle\n            color = #9900ff\n            speed = 300\n        }\n        ",
    "magicCircleScript": ""
  },
  {
    "id": "spell_reimu_non_2",
    "name": "",
    "hp": 1100,
    "duration": 25,
    "x_offset": 0,
    "y_offset": 0,
    "despawnTime": 1.5,
    "emitterScript": "\nwhile (true) {\n    aimAtTarget()\n    spawnRing(\"normal\", \"#ff2255\", 150, angle, 8, 0, 0, 16, \"onmyoutama\", \"relative\", 12)\n    for (let k = 0; k < 3; k++) {\n        spawnRing(\"normal\", \"#ffaa33\", 190 + k * 20, angle + rand(-15, 15), 12, 0, 0, 20, \"ohuda\", \"relative\", 6)\n        wait(0.1)\n    }\n    wait(0.4)\n}\n        ",
    "bulletScript": "\nspeed = 170\n        ",
    "magicCircleScript": ""
  },
  {
    "id": "spell_reimu_2",
    "name": "夢境「二重結界」",
    "hp": 1800,
    "duration": 35,
    "x_offset": 0,
    "y_offset": 0,
    "despawnTime": 1.5,
    "emitterScript": "\nwhile (true) {\n    aimAtTarget()\n    spawnRing(\"normal\", \"#ff3333\", 140, angle, 6, 0, 0, 16, \"onmyoutama\", \"relative\", 12)\n    for (let i = 0; i < 4; i++) {\n        spawnRing(\"normal\", \"#33ccff\", 200, angle + i * 15, 10, 0, 0, 20, \"ohuda\", \"relative\", 6)\n        wait(0.12)\n    }\n    wait(0.6)\n}\n        ",
    "bulletScript": "\nspeed = 180\nbounce()\nspriteAngle = angle\nif (isBounced) {\n    color = \"#ff8800\"\n    speed = 220\n}\n        ",
    "magicCircleScript": ""
  },
  {
    "id": "spell_rush1_non_1",
    "name": "",
    "hp": 1000,
    "duration": 40,
    "x_offset": 0,
    "y_offset": 0,
    "despawnTime": 1.5,
    "emitterScript": "\nwhile (true) {\n    ey = 300\n    aimAtTarget()\n    spawnWay(\"normal\", \"#ff3333\", 500, angle, 2, 90, 0, 0, 9, \"dangan\", \"relative\", \"6\")\n    spawnWay(\"normal\", \"#ff3333\", 500, angle, 3, 2, 0, 0, 9, \"dangan\", \"relative\", \"3\")\n    spawnWay(\"normal\", \"#ff3333\", 500, angle + 180, 5, 50, 0, 0, 9, \"dangan\", \"relative\", \"6\")\n    wait(0.0167 * 4)\n}\n        ",
    "bulletScript": "\n        ",
    "magicCircleScript": ""
  },
  {
    "id": "spell_rush1_1",
    "name": "飛翔「ストライクバーン」",
    "hp": 2000,
    "duration": 40,
    "x_offset": 0,
    "y_offset": 0,
    "despawnTime": 1.5,
    "emitterScript": "\n        while (true) {\n    angle = random(0,360)\n    muki = 1\n    spawnRing(\"normal\", \"#999999\", 200, angle, 36, 0, 0, 9, \"dangan\", \"relative\", \"6\")\n    spawnRing(\"normal\", \"#999999\", 300, angle, 36, 0, 0, 9, \"dangan\", \"relative\", \"6\")\n    spawnRing(\"normal\", \"#999999\", 400, angle, 36, 0, 0, 9, \"dangan\", \"relative\", \"6\")\n    spawnRing(\"normal\", \"#999999\", 500, angle, 36, 0, 0, 9, \"dangan\", \"relative\", \"6\")\n    muki = -1\n    spawnRing(\"normal\", \"#999999\", 200, angle, 36, 0, 0, 9, \"dangan\", \"relative\", \"6\")\n    spawnRing(\"normal\", \"#999999\", 300, angle, 36, 0, 0, 9, \"dangan\", \"relative\", \"6\")\n    spawnRing(\"normal\", \"#999999\", 400, angle, 36, 0, 0, 9, \"dangan\", \"relative\", \"6\")\n    spawnRing(\"normal\", \"#999999\", 500, angle, 36, 0, 0, 9, \"dangan\", \"relative\", \"6\")\n    muki = 0\n    spawnRing(\"normal\", \"#ff3333\", 200, angle, 36, 0, 0, 9, \"dangan\", \"relative\", \"6\")\n    spawnRing(\"normal\", \"#ff3333\", 300, angle, 36, 0, 0, 9, \"dangan\", \"relative\", \"6\")\n    spawnRing(\"normal\", \"#ff3333\", 400, angle, 36, 0, 0, 9, \"dangan\", \"relative\", \"6\")\n    spawnRing(\"normal\", \"#ff3333\", 500, angle, 36, 0, 0, 9, \"dangan\", \"relative\", \"6\")\n    wait(1.67)\n}\n        ",
    "bulletScript": "\nif (color==#999999) {\n    if (frame ==20..21) {\n        once {\n            angle += 10 * muki\n            spriteAngle = angle\n        }\n    }\n}\n        ",
    "magicCircleScript": "\n        \n        "
  },
  {
    "id": "spell_rush1_non_2",
    "name": "",
    "hp": 1600,
    "duration": 25,
    "x_offset": 0,
    "y_offset": 0,
    "despawnTime": 1.5,
    "emitterScript": "\nwhile (true) {\nspd = 0\n    for (let i = 0; i < 10; i++) {\n        spawnRing(\"normal\", \"#ff3333\", 300 + spd, angle, 12, 0, 0, 9, \"kunai1\", \"relative\", \"6\")\nangle += 1\nspd -= 5\nwait(0.0167)\n    }\n    angle += 10\n    wait(0.2)\n}\n        ",
    "bulletScript": "\n\n        ",
    "magicCircleScript": ""
  },
  {
    "id": "spell_rush1_2",
    "name": "「バタフライガン」",
    "hp": 1200,
    "duration": 50,
    "x_offset": 0,
    "y_offset": 0,
    "despawnTime": 1.5,
    "emitterScript": "\nwhile (true) {\n    for (let i = 0; i < 30; i++) {\n        spawnBullet(\"normal\", \"#ff3333\", 600, angle, 100, 0, 9, \"dangan\", \"relative\", \"5\")\n        spawnBullet(\"normal\", \"#ff3333\", 600, angle, -100, 0, 9, \"dangan\", \"relative\", \"5\")\n        wait(0.0167 * 2)\n    }\n    wait(0.5)\n    spawnRing(\"normal\", \"#ffdd33\", 200, 0, 36, 0, 0, 30, \"tyoudan\", \"relative\", \"15\")\n    spawnRing(\"normal\", \"#33ff88\", 400, 0, 36, 0, 0, 30, \"tyoudan\", \"relative\", \"15\")\n    spawnRing(\"normal\", \"#3388ff\", 600, 0, 36, 0, 0, 30, \"tyoudan\", \"relative\", \"15\")\n    wait(0.5)\n}\n        ",
    "bulletScript": "\nif (color==#ff3333) {\n    once {\n        aimAtTarget()\n        angle += random(-5,5)\n        spriteAngle = angle\n    }\n}\n        ",
    "magicCircleScript": ""
  },
  {
    "id": "spell_rush1_non_3",
    "name": "",
    "hp": 1600,
    "duration": 25,
    "x_offset": 0,
    "y_offset": 0,
    "despawnTime": 1.5,
    "emitterScript": "\nwhile (true) {\n    aimAtTarget()\n    spawnBullet(\"normal\", \"#ff3333\", 200, angle + angleoffset, 0, 0, 20, \"tyoudan\", \"relative\", \"10\")\n    spawnBullet(\"normal\", \"#ff3333\", 400, angle + angleoffset, 0, 0, 20, \"tyoudan\", \"relative\", \"10\")\n    angleoffset += 10\n    spawnBullet(\"normal\", \"#ff3333\", 200, angle + angleoffset, 0, 0, 20, \"tyoudan\", \"relative\", \"10\")\n    spawnBullet(\"normal\", \"#ff3333\", 400, angle + angleoffset, 0, 0, 20, \"tyoudan\", \"relative\", \"10\")\n    angleoffset += 10\n    wait(0.0167)\n}\n        ",
    "bulletScript": "\n\n        ",
    "magicCircleScript": ""
  },
  {
    "id": "spell_rush1_3",
    "name": "雷撃「破壊電磁砲」",
    "hp": 2500,
    "duration": 50,
    "x_offset": 0,
    "y_offset": 0,
    "despawnTime": 1.5,
    "emitterScript": "\nwhile (true) {\n    aimAtTarget()\n    spawnRing(\"normal\", \"#ff3333\", 200, angle, 18, 0, 0, 6, \"none\", \"relative\", \"#ff3333\")\n    angle += 10\n    spawnRing(\"normal\", \"#ff3333\", 200, angle, 18, 0, 0, 6, \"none\", \"relative\", \"#ff3333\")\n    wait(1)\n    angle = random(0,360)\n    spawnRing(\"normal\", \"#ff3333\", 200, angle, 18, 250, 150, 6, \"none\", \"relative\", \"#ff3333\")\n    angle += 10\n    spawnRing(\"normal\", \"#ff3333\", 200, angle, 18, 250, 150, 6, \"none\", \"relative\", \"#ff3333\")\n    angle = random(0,360)\n    spawnRing(\"normal\", \"#ff3333\", 200, angle, 18, -250, 150, 6, \"none\", \"relative\", \"#ff3333\")\n    angle += 10\n    spawnRing(\"normal\", \"#ff3333\", 200, angle, 18, -250, 150, 6, \"none\", \"relative\", \"#ff3333\")\n    angle = random(0,360)\n    spawnRing(\"normal\", \"#ff3333\", 200, angle, 18, 100, -50, 6, \"none\", \"relative\", \"#ff3333\")\n    angle += 10\n    spawnRing(\"normal\", \"#ff3333\", 200, angle, 18, 100, -50, 6, \"none\", \"relative\", \"#ff3333\")\n    angle = random(0,360)\n    spawnRing(\"normal\", \"#ff3333\", 200, angle, 18, -100, -50, 6, \"none\", \"relative\", \"#ff3333\")\n    angle += 10\n    spawnRing(\"normal\", \"#ff3333\", 200, angle, 18, -100, -50, 6, \"none\", \"relative\", \"#ff3333\")\n    wait(1)\n}\n        ",
    "bulletScript": "\nwarningTime = 1\nactiveTime = 1\nlaserWidth = 12\n        ",
    "magicCircleScript": ""
  },
  {
    "id": "spell_rush1_non_4",
    "name": "",
    "hp": 2000,
    "duration": 25,
    "x_offset": 0,
    "y_offset": 0,
    "despawnTime": 1.5,
    "emitterScript": "\nwhile (true) {\n    for (let i = 0; i < 30; i++) {\n        spd = 0\n        for (let i = 0; i < 3; i++) {\n            spawnRing(\"normal\", \"#ff3333\", 200 + spd, angle, 4, 0, 0, 8, \"dangan\", \"relative\", \"4\")\n            spd += 50\n        }\n        angle += 9.346\n        wait(0.0167 * 3)\n    }\n    wait(0.5)\n    idousakix = 384 + random(-100,100)\n    idousakiy = 200 + random(-100,100)\n    tween(\"ex\", ex, idousakix, \"seconds\", 0.6, \"easeOut\")\n    tween(\"ey\", ey, idousakiy, \"seconds\", 0.6, \"easeOut\")\n    wait(0.8)\n}\n        ",
    "bulletScript": "\n\n        ",
    "magicCircleScript": ""
  },
  {
    "id": "spell_rush1_4",
    "name": "熾烈「弾幕戦争」",
    "hp": 2500,
    "duration": 50,
    "x_offset": 0,
    "y_offset": 0,
    "despawnTime": 1.5,
    "emitterScript": "\nwhile (true) {\n    once {\n        spawnBulletResist(\"normal\", \"#ff3333\", 700, 0, 0, 100, 10, \"knife\", \"absolute\", \"10\")\n        wait(5)\n        spawnBulletResist(\"normal\", \"#ff3333\", 700, 0, 0, 300, 10, \"knife\", \"absolute\", \"10\")\n        wait(5)\n        spawnBulletResist(\"normal\", \"#ff3333\", 700, 0, 0, 500, 10, \"knife\", \"absolute\", \"10\")\n        wait(5)\n        spawnBulletResist(\"normal\", \"#ff3333\", 700, 0, 0, 700, 10, \"knife\", \"absolute\", \"10\")\n        wait(10)\n    }\n    wait(0.1)\n}\nwhile (true) {\n    wait(3)\n    idousakix = 384 + random(-100,100)\n    idousakiy = 200 + random(-100,100)\n    tween(\"ex\", ex, idousakix, \"seconds\", 0.6, \"easeOut\")\n    tween(\"ey\", ey, idousakiy, \"seconds\", 0.6, \"easeOut\")\n}\n        ",
    "bulletScript": "\nif (frame == 1 * n) {\n    spawnBullet(\"normal\", \"#ff3333\", 0, span, 0, 0, 9, \"dangan\", \"relative\", \"6\")\n    span += 10\n}\nbounce()\n        ",
    "magicCircleScript": "\n        if (frame == 70..700) {\n    speed += 1\n}"
  },
  {
    "id": "spell_rush1_non_5",
    "name": "",
    "hp": 1000,
    "duration": 25,
    "x_offset": 0,
    "y_offset": 0,
    "despawnTime": 1.5,
    "emitterScript": "\n\n        ",
    "bulletScript": "\n\n        ",
    "magicCircleScript": ""
  },
  {
    "id": "spell_rush1_5",
    "name": "「5」",
    "hp": 1000,
    "duration": 25,
    "x_offset": 0,
    "y_offset": 0,
    "despawnTime": 1.5,
    "emitterScript": "\n\n        ",
    "bulletScript": "\n\n        ",
    "magicCircleScript": ""
  },
  {
    "id": "spell_rush1_non_6",
    "name": "",
    "hp": 1000,
    "duration": 25,
    "x_offset": 0,
    "y_offset": 0,
    "despawnTime": 1.5,
    "emitterScript": "\n\n        ",
    "bulletScript": "\n\n        ",
    "magicCircleScript": ""
  },
  {
    "id": "spell_rush1_6",
    "name": "「6」",
    "hp": 1000,
    "duration": 25,
    "x_offset": 0,
    "y_offset": 0,
    "despawnTime": 1.5,
    "emitterScript": "\n\n        ",
    "bulletScript": "\n\n        ",
    "magicCircleScript": ""
  },
  {
    "id": "spell_rush1_non_7",
    "name": "",
    "hp": 1000,
    "duration": 25,
    "x_offset": 0,
    "y_offset": 0,
    "despawnTime": 1.5,
    "emitterScript": "\n\n        ",
    "bulletScript": "\n\n        ",
    "magicCircleScript": ""
  },
  {
    "id": "spell_rush1_7",
    "name": "「7」",
    "hp": 1000,
    "duration": 25,
    "x_offset": 0,
    "y_offset": 0,
    "despawnTime": 1.5,
    "emitterScript": "\n\n        ",
    "bulletScript": "\n\n        ",
    "magicCircleScript": ""
  },
  {
    "id": "spell_rush1_non_8",
    "name": "",
    "hp": 1000,
    "duration": 25,
    "x_offset": 0,
    "y_offset": 0,
    "despawnTime": 1.5,
    "emitterScript": "\n\n        ",
    "bulletScript": "\n\n        ",
    "magicCircleScript": ""
  },
  {
    "id": "spell_rush1_8",
    "name": "「8」",
    "hp": 1000,
    "duration": 25,
    "x_offset": 0,
    "y_offset": 0,
    "despawnTime": 1.5,
    "emitterScript": "\n\n        ",
    "bulletScript": "\n\n        ",
    "magicCircleScript": ""
  },
  {
    "id": "spell_rush1_9",
    "name": "「9」",
    "hp": 1000,
    "duration": 25,
    "x_offset": 0,
    "y_offset": 0,
    "despawnTime": 1.5,
    "emitterScript": "\n\n        ",
    "bulletScript": "\n\n        ",
    "magicCircleScript": ""
  },
  {
    "id": "spell_rush1_10",
    "name": "「10」",
    "hp": 1000,
    "duration": 25,
    "x_offset": 0,
    "y_offset": 0,
    "despawnTime": 1.5,
    "emitterScript": "\n\n        ",
    "bulletScript": "\n\n        ",
    "magicCircleScript": ""
  }
];
window.bossDanmakuList = window.compiledBossDanmakuList;

window.compiledBossDanmaku['spell_reimu_non_1'] = window.compiledDanmaku['spell_reimu_non_1'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    if (_util.executeBlock({ type: 'aim_at_target', }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ff3344", speed: "170", angle: "angle", count: "16", offsetX: "0", offsetY: "0", radius: "20", bulletImage: "ohuda", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
      yield;
    }
    state.waitTimer = Math.max(0.0167, 0.35);
    yield;
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#33aaff", speed: "210", angle: "angle + 11.25", count: "16", offsetX: "0", offsetY: "0", radius: "20", bulletImage: "kome", coordMode: "relative", hitRadius: "4", }, state, b, attacker, target, _util)) {
      yield;
    }
    state.waitTimer = Math.max(0.0167, 0.35);
    yield;
  }
};
window.compiledBossDanmaku['spell_reimu_non_1_bullet'] = window.compiledDanmaku['spell_reimu_non_1_bullet'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    vars['speed'] = 170;
    state.waitTimer = Math.max(state.waitTimer || 0, 0.01);
    yield;
  }
};
window.compiledBossDanmaku['spell_reimu_non_1_magic'] = window.compiledDanmaku['spell_reimu_non_1_magic'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};

window.compiledBossDanmaku['spell_reimu_1'] = window.compiledDanmaku['spell_reimu_1'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    if (_util.executeBlock({ type: 'aim_at_target', }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ff4466", speed: "160", angle: "angle", count: "36", offsetX: "0", offsetY: "0", radius: "20", bulletImage: "ohuda", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
      yield;
    }
    state.waitTimer = Math.max(0.0167, 0.2);
    yield;
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ffcc00", speed: "220", angle: "angle + 15", count: "8", offsetX: "0", offsetY: "0", radius: "6", bulletImage: "star", coordMode: "relative", hitRadius: "5", }, state, b, attacker, target, _util)) {
      yield;
    }
    state.waitTimer = Math.max(0.0167, 0.25);
    yield;
  }
};
window.compiledBossDanmaku['spell_reimu_1_bullet'] = window.compiledDanmaku['spell_reimu_1_bullet'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    if ((String((vars.color !== undefined ? vars.color : "")).trim().toLowerCase() === String("#ff4466").trim().toLowerCase())) {
      vars['speed'] = 500;
      let _prev_g_148 = vars['g'];
      for (let _loopIdx_148 = 0, _limit_148 = Math.round(20); _loopIdx_148 < _limit_148; _loopIdx_148++) {
        vars['g'] = _loopIdx_148;
        vars['speed'] = (vars['speed'] || 0) + (-25);
        state.waitTimer = Math.max(0.0167, 0.04);
        yield;
      }
      vars['g'] = _prev_g_148;
      if (_util.executeBlock({ type: 'aim_at_target', }, state, b, attacker, target, _util)) {
        yield;
      }
      state.waitTimer = Math.max(0.0167, 0.2);
      yield;
      vars['spriteAngle'] = (vars.angle !== undefined ? vars.angle : 0);
      vars['color'] = "#ff6600";
    }
    if ((String((vars.color !== undefined ? vars.color : "")).trim().toLowerCase() === String("#ff6600").trim().toLowerCase())) {
      vars['speed'] = 750;
      let _prev_g_149 = vars['g'];
      for (let _loopIdx_149 = 0, _limit_149 = Math.round(20); _loopIdx_149 < _limit_149; _loopIdx_149++) {
        vars['g'] = _loopIdx_149;
        vars['speed'] = (vars['speed'] || 0) + (-25 * 1.5);
        state.waitTimer = Math.max(0.0167, 0.04);
        yield;
      }
      vars['g'] = _prev_g_149;
      if (_util.executeBlock({ type: 'aim_at_target', }, state, b, attacker, target, _util)) {
        yield;
      }
      state.waitTimer = Math.max(0.0167, 0.2);
      yield;
      vars['spriteAngle'] = (vars.angle !== undefined ? vars.angle : 0);
      vars['color'] = "#9900ff";
      vars['speed'] = 300;
    }
    state.waitTimer = Math.max(state.waitTimer || 0, 0.01);
    yield;
  }
};
window.compiledBossDanmaku['spell_reimu_1_magic'] = window.compiledDanmaku['spell_reimu_1_magic'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};

window.compiledBossDanmaku['spell_reimu_non_2'] = window.compiledDanmaku['spell_reimu_non_2'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    if (_util.executeBlock({ type: 'aim_at_target', }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ff2255", speed: "150", angle: "angle", count: "8", offsetX: "0", offsetY: "0", radius: "16", bulletImage: "onmyoutama", coordMode: "relative", hitRadius: "12", }, state, b, attacker, target, _util)) {
      yield;
    }
    let _prev_k_150 = vars['k'];
    for (let _loopIdx_150 = 0, _limit_150 = Math.round(3); _loopIdx_150 < _limit_150; _loopIdx_150++) {
      vars['k'] = _loopIdx_150;
      if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ffaa33", speed: "190 + k * 20", angle: "angle + rand(-15, 15)", count: "12", offsetX: "0", offsetY: "0", radius: "20", bulletImage: "ohuda", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
        yield;
      }
      state.waitTimer = Math.max(0.0167, 0.1);
      yield;
    }
    vars['k'] = _prev_k_150;
    state.waitTimer = Math.max(0.0167, 0.4);
    yield;
  }
};
window.compiledBossDanmaku['spell_reimu_non_2_bullet'] = window.compiledDanmaku['spell_reimu_non_2_bullet'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    vars['speed'] = 170;
    state.waitTimer = Math.max(state.waitTimer || 0, 0.01);
    yield;
  }
};
window.compiledBossDanmaku['spell_reimu_non_2_magic'] = window.compiledDanmaku['spell_reimu_non_2_magic'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};

window.compiledBossDanmaku['spell_reimu_2'] = window.compiledDanmaku['spell_reimu_2'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    if (_util.executeBlock({ type: 'aim_at_target', }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ff3333", speed: "140", angle: "angle", count: "6", offsetX: "0", offsetY: "0", radius: "16", bulletImage: "onmyoutama", coordMode: "relative", hitRadius: "12", }, state, b, attacker, target, _util)) {
      yield;
    }
    let _prev_i_151 = vars['i'];
    for (let _loopIdx_151 = 0, _limit_151 = Math.round(4); _loopIdx_151 < _limit_151; _loopIdx_151++) {
      vars['i'] = _loopIdx_151;
      if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#33ccff", speed: "200", angle: "angle + i * 15", count: "10", offsetX: "0", offsetY: "0", radius: "20", bulletImage: "ohuda", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
        yield;
      }
      state.waitTimer = Math.max(0.0167, 0.12);
      yield;
    }
    vars['i'] = _prev_i_151;
    state.waitTimer = Math.max(0.0167, 0.6);
    yield;
  }
};
window.compiledBossDanmaku['spell_reimu_2_bullet'] = window.compiledDanmaku['spell_reimu_2_bullet'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    vars['speed'] = 180;
    if (_util.executeBlock({ type: 'bounce', }, state, b, attacker, target, _util)) {
      yield;
    }
    vars['spriteAngle'] = (vars.angle !== undefined ? vars.angle : 0);
    if (!!((vars.isBounced !== undefined ? vars.isBounced : 0))) {
      vars['color'] = "#ff8800";
      vars['speed'] = 220;
    }
    state.waitTimer = Math.max(state.waitTimer || 0, 0.01);
    yield;
  }
};
window.compiledBossDanmaku['spell_reimu_2_magic'] = window.compiledDanmaku['spell_reimu_2_magic'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};

window.compiledBossDanmaku['spell_rush1_non_1'] = window.compiledDanmaku['spell_rush1_non_1'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    vars['ey'] = 300;
    if (_util.executeBlock({ type: 'aim_at_target', }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_way', bulletType: "normal", color: "#ff3333", speed: "500", angle: "angle", count: "2", spread: "90", offsetX: "0", offsetY: "0", radius: "9", bulletImage: "dangan", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_way', bulletType: "normal", color: "#ff3333", speed: "500", angle: "angle", count: "3", spread: "2", offsetX: "0", offsetY: "0", radius: "9", bulletImage: "dangan", coordMode: "relative", hitRadius: "3", }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_way', bulletType: "normal", color: "#ff3333", speed: "500", angle: "angle + 180", count: "5", spread: "50", offsetX: "0", offsetY: "0", radius: "9", bulletImage: "dangan", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
      yield;
    }
    state.waitTimer = Math.max(0.0167, 0.0167 * 4);
    yield;
  }
};
window.compiledBossDanmaku['spell_rush1_non_1_bullet'] = window.compiledDanmaku['spell_rush1_non_1_bullet'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};
window.compiledBossDanmaku['spell_rush1_non_1_magic'] = window.compiledDanmaku['spell_rush1_non_1_magic'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};

window.compiledBossDanmaku['spell_rush1_1'] = window.compiledDanmaku['spell_rush1_1'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    vars['angle'] = random(0,360);
    vars['muki'] = 1;
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#999999", speed: "200", angle: "angle", count: "36", offsetX: "0", offsetY: "0", radius: "9", bulletImage: "dangan", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#999999", speed: "300", angle: "angle", count: "36", offsetX: "0", offsetY: "0", radius: "9", bulletImage: "dangan", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#999999", speed: "400", angle: "angle", count: "36", offsetX: "0", offsetY: "0", radius: "9", bulletImage: "dangan", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#999999", speed: "500", angle: "angle", count: "36", offsetX: "0", offsetY: "0", radius: "9", bulletImage: "dangan", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
      yield;
    }
    vars['muki'] = -1;
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#999999", speed: "200", angle: "angle", count: "36", offsetX: "0", offsetY: "0", radius: "9", bulletImage: "dangan", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#999999", speed: "300", angle: "angle", count: "36", offsetX: "0", offsetY: "0", radius: "9", bulletImage: "dangan", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#999999", speed: "400", angle: "angle", count: "36", offsetX: "0", offsetY: "0", radius: "9", bulletImage: "dangan", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#999999", speed: "500", angle: "angle", count: "36", offsetX: "0", offsetY: "0", radius: "9", bulletImage: "dangan", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
      yield;
    }
    vars['muki'] = 0;
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ff3333", speed: "200", angle: "angle", count: "36", offsetX: "0", offsetY: "0", radius: "9", bulletImage: "dangan", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ff3333", speed: "300", angle: "angle", count: "36", offsetX: "0", offsetY: "0", radius: "9", bulletImage: "dangan", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ff3333", speed: "400", angle: "angle", count: "36", offsetX: "0", offsetY: "0", radius: "9", bulletImage: "dangan", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ff3333", speed: "500", angle: "angle", count: "36", offsetX: "0", offsetY: "0", radius: "9", bulletImage: "dangan", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
      yield;
    }
    state.waitTimer = Math.max(0.0167, 1.67);
    yield;
  }
};
window.compiledBossDanmaku['spell_rush1_1_bullet'] = window.compiledDanmaku['spell_rush1_1_bullet'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    if ((String((vars.color !== undefined ? vars.color : "")).trim().toLowerCase() === String("#999999").trim().toLowerCase())) {
      if (!!((((vars.frame !== undefined ? vars.frame : 0)) >= (20) && ((vars.frame !== undefined ? vars.frame : 0)) <= (21)))) {
        if (!state.onceMap) state.onceMap = {};
        if (!state.onceMap['ieaz2b3rj']) {
          state.onceMap['ieaz2b3rj'] = true;
          vars['angle'] = (vars['angle'] || 0) + (10 * (vars.muki !== undefined ? vars.muki : 0));
          vars['spriteAngle'] = (vars.angle !== undefined ? vars.angle : 0);
        }
      }
    }
    state.waitTimer = Math.max(state.waitTimer || 0, 0.01);
    yield;
  }
};
window.compiledBossDanmaku['spell_rush1_1_magic'] = window.compiledDanmaku['spell_rush1_1_magic'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};

window.compiledBossDanmaku['spell_rush1_non_2'] = window.compiledDanmaku['spell_rush1_non_2'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    vars['spd'] = 0;
    let _prev_i_152 = vars['i'];
    for (let _loopIdx_152 = 0, _limit_152 = Math.round(10); _loopIdx_152 < _limit_152; _loopIdx_152++) {
      vars['i'] = _loopIdx_152;
      if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ff3333", speed: "300 + spd", angle: "angle", count: "12", offsetX: "0", offsetY: "0", radius: "9", bulletImage: "kunai1", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
        yield;
      }
      vars['angle'] = (vars['angle'] || 0) + (1);
      vars['spd'] = (vars['spd'] || 0) - (5);
      state.waitTimer = Math.max(0.0167, 0.0167);
      yield;
    }
    vars['i'] = _prev_i_152;
    vars['angle'] = (vars['angle'] || 0) + (10);
    state.waitTimer = Math.max(0.0167, 0.2);
    yield;
  }
};
window.compiledBossDanmaku['spell_rush1_non_2_bullet'] = window.compiledDanmaku['spell_rush1_non_2_bullet'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};
window.compiledBossDanmaku['spell_rush1_non_2_magic'] = window.compiledDanmaku['spell_rush1_non_2_magic'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};

window.compiledBossDanmaku['spell_rush1_2'] = window.compiledDanmaku['spell_rush1_2'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    let _prev_i_153 = vars['i'];
    for (let _loopIdx_153 = 0, _limit_153 = Math.round(30); _loopIdx_153 < _limit_153; _loopIdx_153++) {
      vars['i'] = _loopIdx_153;
      if (_util.executeBlock({ type: 'spawn_bullet', bulletType: "normal", color: "#ff3333", speed: "600", angle: "angle", offsetX: "100", offsetY: "0", radius: "9", bulletImage: "dangan", coordMode: "relative", hitRadius: "5", }, state, b, attacker, target, _util)) {
        yield;
      }
      if (_util.executeBlock({ type: 'spawn_bullet', bulletType: "normal", color: "#ff3333", speed: "600", angle: "angle", offsetX: "-100", offsetY: "0", radius: "9", bulletImage: "dangan", coordMode: "relative", hitRadius: "5", }, state, b, attacker, target, _util)) {
        yield;
      }
      state.waitTimer = Math.max(0.0167, 0.0167 * 2);
      yield;
    }
    vars['i'] = _prev_i_153;
    state.waitTimer = Math.max(0.0167, 0.5);
    yield;
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ffdd33", speed: "200", angle: "0", count: "36", offsetX: "0", offsetY: "0", radius: "30", bulletImage: "tyoudan", coordMode: "relative", hitRadius: "15", }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#33ff88", speed: "400", angle: "0", count: "36", offsetX: "0", offsetY: "0", radius: "30", bulletImage: "tyoudan", coordMode: "relative", hitRadius: "15", }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#3388ff", speed: "600", angle: "0", count: "36", offsetX: "0", offsetY: "0", radius: "30", bulletImage: "tyoudan", coordMode: "relative", hitRadius: "15", }, state, b, attacker, target, _util)) {
      yield;
    }
    state.waitTimer = Math.max(0.0167, 0.5);
    yield;
  }
};
window.compiledBossDanmaku['spell_rush1_2_bullet'] = window.compiledDanmaku['spell_rush1_2_bullet'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    if ((String((vars.color !== undefined ? vars.color : "")).trim().toLowerCase() === String("#ff3333").trim().toLowerCase())) {
      if (!state.onceMap) state.onceMap = {};
      if (!state.onceMap['140m0sdi3']) {
        state.onceMap['140m0sdi3'] = true;
        if (_util.executeBlock({ type: 'aim_at_target', }, state, b, attacker, target, _util)) {
          yield;
        }
        vars['angle'] = (vars['angle'] || 0) + (random(-5,5));
        vars['spriteAngle'] = (vars.angle !== undefined ? vars.angle : 0);
      }
    }
    state.waitTimer = Math.max(state.waitTimer || 0, 0.01);
    yield;
  }
};
window.compiledBossDanmaku['spell_rush1_2_magic'] = window.compiledDanmaku['spell_rush1_2_magic'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};

window.compiledBossDanmaku['spell_rush1_non_3'] = window.compiledDanmaku['spell_rush1_non_3'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    if (_util.executeBlock({ type: 'aim_at_target', }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_bullet', bulletType: "normal", color: "#ff3333", speed: "200", angle: "angle + angleoffset", offsetX: "0", offsetY: "0", radius: "20", bulletImage: "tyoudan", coordMode: "relative", hitRadius: "10", }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_bullet', bulletType: "normal", color: "#ff3333", speed: "400", angle: "angle + angleoffset", offsetX: "0", offsetY: "0", radius: "20", bulletImage: "tyoudan", coordMode: "relative", hitRadius: "10", }, state, b, attacker, target, _util)) {
      yield;
    }
    vars['angleoffset'] = (vars['angleoffset'] || 0) + (10);
    if (_util.executeBlock({ type: 'spawn_bullet', bulletType: "normal", color: "#ff3333", speed: "200", angle: "angle + angleoffset", offsetX: "0", offsetY: "0", radius: "20", bulletImage: "tyoudan", coordMode: "relative", hitRadius: "10", }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_bullet', bulletType: "normal", color: "#ff3333", speed: "400", angle: "angle + angleoffset", offsetX: "0", offsetY: "0", radius: "20", bulletImage: "tyoudan", coordMode: "relative", hitRadius: "10", }, state, b, attacker, target, _util)) {
      yield;
    }
    vars['angleoffset'] = (vars['angleoffset'] || 0) + (10);
    state.waitTimer = Math.max(0.0167, 0.0167);
    yield;
  }
};
window.compiledBossDanmaku['spell_rush1_non_3_bullet'] = window.compiledDanmaku['spell_rush1_non_3_bullet'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};
window.compiledBossDanmaku['spell_rush1_non_3_magic'] = window.compiledDanmaku['spell_rush1_non_3_magic'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};

window.compiledBossDanmaku['spell_rush1_3'] = window.compiledDanmaku['spell_rush1_3'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    if (_util.executeBlock({ type: 'aim_at_target', }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ff3333", speed: "200", angle: "angle", count: "18", offsetX: "0", offsetY: "0", radius: "6", bulletImage: "none", coordMode: "relative", hitRadius: "#ff3333", }, state, b, attacker, target, _util)) {
      yield;
    }
    vars['angle'] = (vars['angle'] || 0) + (10);
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ff3333", speed: "200", angle: "angle", count: "18", offsetX: "0", offsetY: "0", radius: "6", bulletImage: "none", coordMode: "relative", hitRadius: "#ff3333", }, state, b, attacker, target, _util)) {
      yield;
    }
    state.waitTimer = Math.max(0.0167, 1);
    yield;
    vars['angle'] = random(0,360);
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ff3333", speed: "200", angle: "angle", count: "18", offsetX: "250", offsetY: "150", radius: "6", bulletImage: "none", coordMode: "relative", hitRadius: "#ff3333", }, state, b, attacker, target, _util)) {
      yield;
    }
    vars['angle'] = (vars['angle'] || 0) + (10);
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ff3333", speed: "200", angle: "angle", count: "18", offsetX: "250", offsetY: "150", radius: "6", bulletImage: "none", coordMode: "relative", hitRadius: "#ff3333", }, state, b, attacker, target, _util)) {
      yield;
    }
    vars['angle'] = random(0,360);
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ff3333", speed: "200", angle: "angle", count: "18", offsetX: "-250", offsetY: "150", radius: "6", bulletImage: "none", coordMode: "relative", hitRadius: "#ff3333", }, state, b, attacker, target, _util)) {
      yield;
    }
    vars['angle'] = (vars['angle'] || 0) + (10);
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ff3333", speed: "200", angle: "angle", count: "18", offsetX: "-250", offsetY: "150", radius: "6", bulletImage: "none", coordMode: "relative", hitRadius: "#ff3333", }, state, b, attacker, target, _util)) {
      yield;
    }
    vars['angle'] = random(0,360);
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ff3333", speed: "200", angle: "angle", count: "18", offsetX: "100", offsetY: "-50", radius: "6", bulletImage: "none", coordMode: "relative", hitRadius: "#ff3333", }, state, b, attacker, target, _util)) {
      yield;
    }
    vars['angle'] = (vars['angle'] || 0) + (10);
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ff3333", speed: "200", angle: "angle", count: "18", offsetX: "100", offsetY: "-50", radius: "6", bulletImage: "none", coordMode: "relative", hitRadius: "#ff3333", }, state, b, attacker, target, _util)) {
      yield;
    }
    vars['angle'] = random(0,360);
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ff3333", speed: "200", angle: "angle", count: "18", offsetX: "-100", offsetY: "-50", radius: "6", bulletImage: "none", coordMode: "relative", hitRadius: "#ff3333", }, state, b, attacker, target, _util)) {
      yield;
    }
    vars['angle'] = (vars['angle'] || 0) + (10);
    if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ff3333", speed: "200", angle: "angle", count: "18", offsetX: "-100", offsetY: "-50", radius: "6", bulletImage: "none", coordMode: "relative", hitRadius: "#ff3333", }, state, b, attacker, target, _util)) {
      yield;
    }
    state.waitTimer = Math.max(0.0167, 1);
    yield;
  }
};
window.compiledBossDanmaku['spell_rush1_3_bullet'] = window.compiledDanmaku['spell_rush1_3_bullet'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    if (_util.executeBlock({ type: 'set_laser', warningTime: "1", activeTime: "1", laserWidth: "12", }, state, b, attacker, target, _util)) {
      yield;
    }
    state.waitTimer = Math.max(state.waitTimer || 0, 0.01);
    yield;
  }
};
window.compiledBossDanmaku['spell_rush1_3_magic'] = window.compiledDanmaku['spell_rush1_3_magic'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};

window.compiledBossDanmaku['spell_rush1_non_4'] = window.compiledDanmaku['spell_rush1_non_4'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    let _prev_i_154 = vars['i'];
    for (let _loopIdx_154 = 0, _limit_154 = Math.round(30); _loopIdx_154 < _limit_154; _loopIdx_154++) {
      vars['i'] = _loopIdx_154;
      vars['spd'] = 0;
      let _prev_i_155 = vars['i'];
      for (let _loopIdx_155 = 0, _limit_155 = Math.round(3); _loopIdx_155 < _limit_155; _loopIdx_155++) {
        vars['i'] = _loopIdx_155;
        if (_util.executeBlock({ type: 'spawn_ring', bulletType: "normal", color: "#ff3333", speed: "200 + spd", angle: "angle", count: "4", offsetX: "0", offsetY: "0", radius: "8", bulletImage: "dangan", coordMode: "relative", hitRadius: "4", }, state, b, attacker, target, _util)) {
          yield;
        }
        vars['spd'] = (vars['spd'] || 0) + (50);
      }
      vars['i'] = _prev_i_155;
      vars['angle'] = (vars['angle'] || 0) + (9.346);
      state.waitTimer = Math.max(0.0167, 0.0167 * 3);
      yield;
    }
    vars['i'] = _prev_i_154;
    state.waitTimer = Math.max(0.0167, 0.5);
    yield;
    vars['idousakix'] = 384 + random(-100,100);
    vars['idousakiy'] = 200 + random(-100,100);
    if (_util.executeBlock({ type: 'tween_var', name: "ex", from: "ex", to: "idousakix", mode: "seconds", duration: "0.6", stepVal: "5", easing: "easeOut", }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'tween_var', name: "ey", from: "ey", to: "idousakiy", mode: "seconds", duration: "0.6", stepVal: "5", easing: "easeOut", }, state, b, attacker, target, _util)) {
      yield;
    }
    state.waitTimer = Math.max(0.0167, 0.8);
    yield;
  }
};
window.compiledBossDanmaku['spell_rush1_non_4_bullet'] = window.compiledDanmaku['spell_rush1_non_4_bullet'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};
window.compiledBossDanmaku['spell_rush1_non_4_magic'] = window.compiledDanmaku['spell_rush1_non_4_magic'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};

window.compiledBossDanmaku['spell_rush1_4'] = window.compiledDanmaku['spell_rush1_4'] = [
  function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    if (!state.onceMap) state.onceMap = {};
    if (!state.onceMap['whydmshqu']) {
      state.onceMap['whydmshqu'] = true;
      if (_util.executeBlock({ type: 'spawn_bullet_resist', bulletType: "normal", color: "#ff3333", speed: "700", angle: "0", offsetX: "0", offsetY: "100", radius: "10", bulletImage: "knife", coordMode: "absolute", hitRadius: "10", }, state, b, attacker, target, _util)) {
        yield;
      }
      state.waitTimer = Math.max(0.0167, 5);
      yield;
      if (_util.executeBlock({ type: 'spawn_bullet_resist', bulletType: "normal", color: "#ff3333", speed: "700", angle: "0", offsetX: "0", offsetY: "300", radius: "10", bulletImage: "knife", coordMode: "absolute", hitRadius: "10", }, state, b, attacker, target, _util)) {
        yield;
      }
      state.waitTimer = Math.max(0.0167, 5);
      yield;
      if (_util.executeBlock({ type: 'spawn_bullet_resist', bulletType: "normal", color: "#ff3333", speed: "700", angle: "0", offsetX: "0", offsetY: "500", radius: "10", bulletImage: "knife", coordMode: "absolute", hitRadius: "10", }, state, b, attacker, target, _util)) {
        yield;
      }
      state.waitTimer = Math.max(0.0167, 5);
      yield;
      if (_util.executeBlock({ type: 'spawn_bullet_resist', bulletType: "normal", color: "#ff3333", speed: "700", angle: "0", offsetX: "0", offsetY: "700", radius: "10", bulletImage: "knife", coordMode: "absolute", hitRadius: "10", }, state, b, attacker, target, _util)) {
        yield;
      }
      state.waitTimer = Math.max(0.0167, 10);
      yield;
    }
    state.waitTimer = Math.max(0.0167, 0.1);
    yield;
  }
},
  function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    state.waitTimer = Math.max(0.0167, 3);
    yield;
    vars['idousakix'] = 384 + random(-100,100);
    vars['idousakiy'] = 200 + random(-100,100);
    if (_util.executeBlock({ type: 'tween_var', name: "ex", from: "ex", to: "idousakix", mode: "seconds", duration: "0.6", stepVal: "5", easing: "easeOut", }, state, b, attacker, target, _util)) {
      yield;
    }
    if (_util.executeBlock({ type: 'tween_var', name: "ey", from: "ey", to: "idousakiy", mode: "seconds", duration: "0.6", stepVal: "5", easing: "easeOut", }, state, b, attacker, target, _util)) {
      yield;
    }
  }
}
];
window.compiledBossDanmaku['spell_rush1_4_bullet'] = window.compiledDanmaku['spell_rush1_4_bullet'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    if (!!((vars.n !== undefined ? (vars.frame === 1 * vars.n) : (Math.round(vars.frame / 1) >= 1 && Math.abs(vars.frame - 1 * Math.round(vars.frame / 1)) < 0.017)))) {
      if (_util.executeBlock({ type: 'spawn_bullet', bulletType: "normal", color: "#ff3333", speed: "0", angle: "span", offsetX: "0", offsetY: "0", radius: "9", bulletImage: "dangan", coordMode: "relative", hitRadius: "6", }, state, b, attacker, target, _util)) {
        yield;
      }
      vars['span'] = (vars['span'] || 0) + (10);
    }
    if (_util.executeBlock({ type: 'bounce', }, state, b, attacker, target, _util)) {
      yield;
    }
    state.waitTimer = Math.max(state.waitTimer || 0, 0.01);
    yield;
  }
};
window.compiledBossDanmaku['spell_rush1_4_magic'] = window.compiledDanmaku['spell_rush1_4_magic'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
  while (true) {
    if (!!((((vars.frame !== undefined ? vars.frame : 0)) >= (70) && ((vars.frame !== undefined ? vars.frame : 0)) <= (700)))) {
      vars['speed'] = (vars['speed'] || 0) + (1);
    }
    state.waitTimer = Math.max(state.waitTimer || 0, 0.01);
    yield;
  }
};

window.compiledBossDanmaku['spell_rush1_non_5'] = window.compiledDanmaku['spell_rush1_non_5'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};
window.compiledBossDanmaku['spell_rush1_non_5_bullet'] = window.compiledDanmaku['spell_rush1_non_5_bullet'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};
window.compiledBossDanmaku['spell_rush1_non_5_magic'] = window.compiledDanmaku['spell_rush1_non_5_magic'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};

window.compiledBossDanmaku['spell_rush1_5'] = window.compiledDanmaku['spell_rush1_5'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};
window.compiledBossDanmaku['spell_rush1_5_bullet'] = window.compiledDanmaku['spell_rush1_5_bullet'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};
window.compiledBossDanmaku['spell_rush1_5_magic'] = window.compiledDanmaku['spell_rush1_5_magic'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};

window.compiledBossDanmaku['spell_rush1_non_6'] = window.compiledDanmaku['spell_rush1_non_6'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};
window.compiledBossDanmaku['spell_rush1_non_6_bullet'] = window.compiledDanmaku['spell_rush1_non_6_bullet'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};
window.compiledBossDanmaku['spell_rush1_non_6_magic'] = window.compiledDanmaku['spell_rush1_non_6_magic'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};

window.compiledBossDanmaku['spell_rush1_6'] = window.compiledDanmaku['spell_rush1_6'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};
window.compiledBossDanmaku['spell_rush1_6_bullet'] = window.compiledDanmaku['spell_rush1_6_bullet'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};
window.compiledBossDanmaku['spell_rush1_6_magic'] = window.compiledDanmaku['spell_rush1_6_magic'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};

window.compiledBossDanmaku['spell_rush1_non_7'] = window.compiledDanmaku['spell_rush1_non_7'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};
window.compiledBossDanmaku['spell_rush1_non_7_bullet'] = window.compiledDanmaku['spell_rush1_non_7_bullet'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};
window.compiledBossDanmaku['spell_rush1_non_7_magic'] = window.compiledDanmaku['spell_rush1_non_7_magic'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};

window.compiledBossDanmaku['spell_rush1_7'] = window.compiledDanmaku['spell_rush1_7'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};
window.compiledBossDanmaku['spell_rush1_7_bullet'] = window.compiledDanmaku['spell_rush1_7_bullet'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};
window.compiledBossDanmaku['spell_rush1_7_magic'] = window.compiledDanmaku['spell_rush1_7_magic'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};

window.compiledBossDanmaku['spell_rush1_non_8'] = window.compiledDanmaku['spell_rush1_non_8'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};
window.compiledBossDanmaku['spell_rush1_non_8_bullet'] = window.compiledDanmaku['spell_rush1_non_8_bullet'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};
window.compiledBossDanmaku['spell_rush1_non_8_magic'] = window.compiledDanmaku['spell_rush1_non_8_magic'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};

window.compiledBossDanmaku['spell_rush1_8'] = window.compiledDanmaku['spell_rush1_8'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};
window.compiledBossDanmaku['spell_rush1_8_bullet'] = window.compiledDanmaku['spell_rush1_8_bullet'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};
window.compiledBossDanmaku['spell_rush1_8_magic'] = window.compiledDanmaku['spell_rush1_8_magic'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};

window.compiledBossDanmaku['spell_rush1_9'] = window.compiledDanmaku['spell_rush1_9'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};
window.compiledBossDanmaku['spell_rush1_9_bullet'] = window.compiledDanmaku['spell_rush1_9_bullet'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};
window.compiledBossDanmaku['spell_rush1_9_magic'] = window.compiledDanmaku['spell_rush1_9_magic'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};

window.compiledBossDanmaku['spell_rush1_10'] = window.compiledDanmaku['spell_rush1_10'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};
window.compiledBossDanmaku['spell_rush1_10_bullet'] = window.compiledDanmaku['spell_rush1_10_bullet'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};
window.compiledBossDanmaku['spell_rush1_10_magic'] = window.compiledDanmaku['spell_rush1_10_magic'] = function*(state, b, attacker, target, _util) {
  let vars = state.variables;
  const random = _util.rand;
  const rand = _util.rand;
  const seedrandom = _util.seedrandom;
};

