const fs = require('fs');
const path = require('path');

// Mocks for browser environment so game.js and editor.js can run in Node
global.window = global;
global.addEventListener = () => {};
global.document = { addEventListener: () => {},
    getElementById: (id) => ({
        getContext: () => ({
            fillRect: () => {},
            clearRect: () => {},
            drawImage: () => {},
            fillText: () => {},
            measureText: () => ({ width: 0 }),
            beginPath: () => {},
            arc: () => {},
            fill: () => {},
            stroke: () => {},
            save: () => {},
            restore: () => {},
            translate: () => {},
            rotate: () => {},
            scale: () => {}
        }),
        addEventListener: () => {},
        width: 640,
        height: 960,
        style: {},
        classList: { add: () => {}, remove: () => {}, contains: () => false },
        value: ''
    }),
    createElement: () => ({
        getContext: () => ({}),
        style: {}
    }),
    querySelector: () => null,
    querySelectorAll: () => []
};
global.Image = class {};
global.Audio = class {
    constructor() { this.src = ''; }
    play() {}
    pause() {}
    cloneNode() { return new Audio(); }
};
global.requestAnimationFrame = () => {};
global.cancelAnimationFrame = () => {};
global.localStorage = { getItem: () => null, setItem: () => {} };
global.navigator = { userAgent: '' };

const jsDir = path.join(__dirname, '..', 'js');

// Load files
const gameJs = fs.readFileSync(path.join(jsDir, 'game.js'), 'utf8');
const editorJs = fs.readFileSync(path.join(jsDir, 'editor.js'), 'utf8');
const compilerJs = fs.readFileSync(path.join(jsDir, 'compiler.js'), 'utf8');
const danmakuJs = fs.readFileSync(path.join(jsDir, 'danmaku.js'), 'utf8');
const emitterJs = fs.readFileSync(path.join(jsDir, 'emitter.js'), 'utf8');

// Evaluate in global scope
eval(gameJs);
eval(editorJs);
eval(compilerJs);
eval(danmakuJs + ';\nwindow.sharedDanmakuList = sharedDanmakuList;');

function compileDanmakuToJS() {
    console.log("Compiling danmaku...");
    try {
        let emitterText = emitterJs;

        let switchMatches = [...emitterText.matchAll(/switch\s*\(\s*block\.type\s*\)\s*\{/g)];
        if (switchMatches.length === 0) {
            console.error("Could not find the switch statement in executeBlock!");
            return;
        }

        let startIndex = switchMatches[1].index;
        let braceCount = 0;
        let endIndex = -1;
        let started = false;

        for (let i = startIndex; i < emitterText.length; i++) {
            if (emitterText[i] === '{') {
                braceCount++;
                started = true;
            } else if (emitterText[i] === '}') {
                braceCount--;
                if (started && braceCount === 0) {
                    endIndex = i;
                    break;
                }
            }
        }

        let switchBody = emitterText.substring(startIndex, endIndex + 1);
        let runtimeBlocksCode = switchBody;
        runtimeBlocksCode = runtimeBlocksCode.replace(/block\.params/g, 'p');
        runtimeBlocksCode = runtimeBlocksCode.replace(/block\.type/g, 'p.type');
        runtimeBlocksCode = runtimeBlocksCode.replace(/block\.children/g, 'p.children');
        runtimeBlocksCode = runtimeBlocksCode.replace(/resolveColorParam\(/g, 'window.DanmakuCompilerRuntime.resolveColorParam(');

        let outputJS = `// ==========================================
// PRE-COMPILED DANMAKU GENERATORS
// Auto-generated by tools/compile.js
// ==========================================

window.compiledDanmaku = window.compiledDanmaku || {};
window.DanmakuCompilerRuntime = window.DanmakuCompilerRuntime || {};

// Helpers
window.DanmakuCompilerRuntime.resolveColorParam = function(val, vars) {
    if (!val) return null;
    let s = String(val);
    if (s.startsWith('#')) return s;
    if (vars && vars[s]) return String(vars[s]);
    return s;
};

// 実行エンジン (extracted from emitter.js)
window.DanmakuCompilerRuntime.executeBlock = function(p, state, b, attacker, target, _util) {
    let isPlayerSide = state.isPlayerSide;
    let canvas = window.canvas || {width: 640, height: 960};
    let block = p;
    let brokeToWait = false;
    let advancePC = true;
    
    ${runtimeBlocksCode}
    
    return brokeToWait;
};

window.DanmakuCompilerRuntime.fuzzyEqual = function(a, b) {
    let sa = String(a).trim().toLowerCase();
    let sb = String(b).trim().toLowerCase();
    if (sa === sb) return true;
    let na = Number(sa);
    let nb = Number(sb);
    if (!isNaN(na) && !isNaN(nb)) return Math.abs(na - nb) < 0.0001;
    return false;
};
window.DanmakuCompilerRuntime.fuzzyNotEqual = function(a, b) { return !window.DanmakuCompilerRuntime.fuzzyEqual(a, b); };
window.DanmakuCompilerRuntime.seedrandom = function(seed, a, b, vars) { return Math.random(); };

`;

        let compiledCount = 0;
        for (let danmaku of window.sharedDanmakuList) {
            let idx = window.sharedDanmakuList.indexOf(danmaku);
            let id = danmaku.id || ('danmaku_' + idx);
            
            let blocks = typeof window.codeToBlocks === 'function' ? window.codeToBlocks(danmaku.emitterScript) : [];
            let compiledBlocks = typeof window.compileIndentedBlocks === 'function' ? window.compileIndentedBlocks(JSON.parse(JSON.stringify(blocks))) : [];

            let funcStr = window.DanmakuCompiler.compileSingle(compiledBlocks);
            
            outputJS += `window.compiledDanmaku['${id}'] = ${funcStr};\n\n`;
            compiledCount++;
        }

        fs.writeFileSync(path.join(jsDir, 'compiledanmaku.js'), outputJS, 'utf8');
        console.log(`Successfully compiled ${compiledCount} danmaku scripts to js/compiledanmaku.js!`);
        
    } catch (e) {
        console.error("Compilation failed:", e);
    }
}

compileDanmakuToJS();
